# -*- coding: utf-8 -*-
"""assigment 6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nCVo-3ljxqJpR4d8VA1eoOftjU-6JtDO
"""



"""Kullanıcıdan bir sayı alan ve asal sayı olup olmadığını kontrol etmek için sonucu yazdıran bir program yazın .


"""

number = int(input("enter a number :"))
number>1
for i in range(2,number) :
   if number % i == 0 :
    print("number is not prime")
    break
else :
    print("number is prime")





























